name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - master
jobs:
  terraform init:
    name: 'Terraform Init'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.1.2
          tf_actions_subcommand: 'init'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  terraform Validate:
    name: 'Terraform Validate'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Validation'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.1.2
          tf_actions_subcommand: 'validate'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  terraform Plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Planning'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.1.2
          tf_actions_subcommand: 'plan'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}