name: 'Terraform GitHub Actions'
  on:
    push:
      branches:
        - master
jobs:
   terraform:
     name: 'Terraform'
     runs-on: ubuntu-latest
     defaults:
      run:
        shell: bash
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.1.2
          tf_actions_subcommand: 'init'

#      - name: 'Terraform Validation'
#        uses: hashicorp/terraform-github-actions@master
#        with:
#          tf_actions_version: 1.1.2
#          tf_actions_subcommand: 'validate'
#      - name: 'Terraform Planning'
#        uses: hashicorp/terraform-github-actions@master
#        with:
#          tf_actions_version: 1.1.2
#          tf_actions_subcommand: 'plan'
#      - name: 'Terraform Apply'
#        uses: hashicorp/terraform-github-actions@master
#        with:
#          tf_actions_version: 1.1.2
#          tf_actions_subcommand: 'apply'
      - name: 'Terraform Destroy'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.1.2
          tf_actions_subcommand: 'destroy'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}