name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - master
jobs:
  terraform:
    name: 'Terraform init'
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.2.1
          tf_actions_subcommand: 'init'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}